[package]
name = "todo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
askama = "0.11.1"
thiserror = "1.0.37"
diesel = { version = "*", features = ["mysql"] }
dotenvy = "0.15.6"
